### PR TITLE
#2 made Encryption not browsable

### PR DESCRIPTION
**Pull request by AmenJlili**
This addresses the issue in #2.

### CODE REVIEW

**Comment by SoftCircuits** [comment]
I have merged your change.

**Comment by AmenJlili** [comment]
Thanks. Do you think you can push a new version to nuget.org?

**Comment by SoftCircuits** [comment]
Yes, I can. But I can't do it right now.

**Comment by AmenJlili** [comment]
No rush. You can drop this to nuget.org

https://u.pcloud.link/publink/show?code=XZJ8kFVZ8EhR6zkGflhsnwtcgIoclRbkFfR7

**Comment by AmenJlili** [comment]
@SoftCircuits : This works perfect with 3.0.1. Thanks!

**Pull request merged**
